spring:
  application:
    name: manifest-reader-user
  config:
    import: optional:classpath:dev.yml

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

manifest:
  user:
    mybatis:
      enabled: ${USER_MYBATIS_ENABLED:true}
